// Reflection - single-header distribution
// Generated by tools/amalgamate.py. Do not edit manually.
//
// MIT License
//
// Copyright (c) 2026 Mars Rooll
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <type_traits>
#include <array>
#include <utility>
#include <string>
#include <string_view>
#include <cstddef>

namespace reflection
{

// ========================================================================
// reflection/utils/canonicalstaticstring.h
// ========================================================================
template <typename T, T... chars>
struct CanonicalStaticStringHolder
{
    static constexpr T value[] = {chars..., '\0'};
};

namespace impl
{

template <typename T>
constexpr std::size_t canonicalStaticStringLength(const T* str)
{
    std::size_t size = 0;
    while (str[size])
        ++size;

    return size;
}

template <typename T, const T* str, std::size_t... indices>
auto makeCanonicalStaticString(std::index_sequence<indices...>)
    -> CanonicalStaticStringHolder<T, str[indices]...>;

template <
    typename T,
    const T* str,
    std::size_t begin,
    std::size_t... indices>
auto makeCanonicalStaticStringRange(
    std::index_sequence<indices...>)
    -> CanonicalStaticStringHolder<
        T,
        str[begin + indices]...>;

template <
    typename T,
    const T* str1,
    const T* str2,
    std::size_t... indices1,
    std::size_t... indices2>
auto concatCanonicalStaticString(
    std::index_sequence<indices1...>,
    std::index_sequence<indices2...>)
    -> CanonicalStaticStringHolder<
        T,
        str1[indices1]...,
        str2[indices2]...>;

} // namespace impl

template <const char* str>
using CanonicalStaticString =
    decltype(impl::makeCanonicalStaticString<char, str>(
        std::make_index_sequence<impl::canonicalStaticStringLength(str)>{}));

template <
    const char* str,
    std::size_t begin,
    std::size_t length>
using CanonicalStaticStringRange =
    decltype(
        impl::makeCanonicalStaticStringRange<
            char,
            str,
            begin>(
            std::make_index_sequence<length>{}));

template <const char* str1, const char* str2>
using CanonicalStaticStringConcat =
    decltype(impl::concatCanonicalStaticString<char, str1, str2>(
    std::make_index_sequence<impl::canonicalStaticStringLength(str1)>{},
    std::make_index_sequence<impl::canonicalStaticStringLength(str2)>{}));

// ========================================================================
// reflection/utils/canonicalpropertynameparser.h
// ========================================================================
namespace impl
{

template <typename T, const T* propertyNames>
struct CanonicalPropertyNameParserImpl
{
    static_assert(propertyNames != nullptr);

    struct StaticPropertyNameRange
    {
        std::size_t begin;
        std::size_t end;
    };

    static constexpr bool isCharIdentifier(T c)
    {
        return
            (c >= 'a' && c <= 'z') ||
            (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') ||
            c == '_';
    }

    static constexpr bool isCharDelimiter(T c)
    {
        return c == ',';
    }

    static constexpr std::size_t getNamesCount()
    {
        if constexpr (propertyNames == nullptr
            || propertyNames[0] == static_cast<T>('\0'))
        {
            return 0;
        }
        else
        {
            std::size_t count = 1;
            std::size_t templateDepth = 0;
            bool containsIdentifier = false;

            for (std::size_t index = 0; propertyNames[index]; ++index)
            {
                const auto c = propertyNames[index];

                if (c == '<')
                {
                    ++templateDepth;
                }
                else if (c == '>')
                {
                    if (templateDepth == 0)
                        return 0;

                    --templateDepth;
                }
                else if (templateDepth == 0)
                {
                    if (isCharDelimiter(c))
                    {
                        if (!containsIdentifier)
                            return 0;

                        ++count;
                        containsIdentifier = false;
                    }
                    else if (isCharIdentifier(c))
                    {
                        containsIdentifier = true;
                    }
                }
            }

            if (!(templateDepth == 0 && containsIdentifier))
            {
                return 0;
            }

            return count;
        }
    }

    static constexpr std::size_t count = getNamesCount();
    static_assert(count != 0, "CanonicalPropertyNameParser: unexpected empty propertyNames");

    using NameRangesArray = std::array<StaticPropertyNameRange, count>;

    static constexpr NameRangesArray getNameRangesArray()
    {
        NameRangesArray array{};

        std::size_t rangeIndex = 0;
        std::size_t index = 0;
        std::size_t templateDepth = 0;

        std::size_t argumentBegin = 0;
        std::size_t argumentEnd = 0;

        bool shouldResetArgument = false;

        while (propertyNames[index])
        {
            const auto c = propertyNames[index];

            if (c == '<')
            {
                ++templateDepth;
                shouldResetArgument = true;
            }
            else if (c == '>')
            {
                --templateDepth;
                shouldResetArgument = true;
            }
            else if (templateDepth == 0)
            {
                if (isCharDelimiter(c))
                {
                    if (!(argumentBegin < argumentEnd && rangeIndex < count))
                        return {};

                    array.at(rangeIndex) = { argumentBegin, argumentEnd };

                    ++rangeIndex;
                    shouldResetArgument = true;
                }
                else if (isCharIdentifier(c))
                {
                    if (shouldResetArgument || argumentBegin == argumentEnd)
                    {
                        argumentBegin = index;
                        argumentEnd = index + 1;
                        shouldResetArgument = false;
                    }
                    else
                    {
                        ++argumentEnd;
                    }
                }
                else
                {
                    shouldResetArgument = true;
                }
            }

            ++index;
        }

        if (!(argumentBegin < argumentEnd && rangeIndex < count))
            return {};

        array.at(rangeIndex) = { argumentBegin, argumentEnd };

        return array;
    }

    static constexpr NameRangesArray nameRangesArray = getNameRangesArray();
    static_assert(nameRangesArray[0].begin < nameRangesArray[0].end,
                  "CanonicalPropertyNameParser: unexpected empty nameRangesArray");

    template <std::size_t index>
    using CanonicalName = CanonicalStaticStringRange<
        propertyNames,
        nameRangesArray[index].begin,
        nameRangesArray[index].end
            - nameRangesArray[index].begin>;
};

} // namespace impl

template <const auto* propertyNames>
using CanonicalPropertyNameParser = impl::CanonicalPropertyNameParserImpl<
    std::remove_cv_t<std::remove_pointer_t<decltype(propertyNames)>>,
    propertyNames>;

// ========================================================================
// reflection/utils/typetraits.h
// ========================================================================
template <typename T>
struct IsString
    : std::disjunction<
        std::is_same<T, std::string>,
        std::is_same<T, std::string_view>> {};

template <typename Test, template<typename...> typename Ref>
struct IsSpecialization : std::false_type {};

template <template<typename...> typename Ref, typename... Args>
struct IsSpecialization<Ref<Args...>, Ref> : std::true_type {};

template <typename Test, template<typename, std::size_t> typename Ref>
struct IsSpecializationSized : std::false_type {};

template <template<typename, std::size_t> typename Ref, typename Arg, std::size_t Num>
struct IsSpecializationSized<Ref<Arg, Num>, Ref> : std::true_type {};

template <typename T, typename = std::void_t<>>
struct IsIterable : std::false_type {};

template <typename T>
struct IsIterable<T, std::void_t<
    decltype(std::begin(std::declval<T&>())),
    decltype(std::end(std::declval<T&>())),
    decltype(++std::declval<decltype(std::begin(std::declval<T&>()))&>())>> : std::true_type {};

template <typename T, typename = std::void_t<>>
struct IsInsertable : std::false_type {};

template <typename T>
struct IsInsertable<T, std::void_t<
    typename T::value_type,
    typename T::iterator,
    decltype(std::declval<T&>().insert(
        std::declval<typename T::iterator>(),
        std::declval<typename T::value_type>()))>> : std::true_type {};

template <typename T, typename = std::void_t<>>
struct HasReserve : std::false_type {};

template <typename T>
struct HasReserve<T, std::void_t<
    decltype(std::declval<T&>().reserve(std::declval<std::size_t>()))>> : std::true_type {};

template <typename T, typename = std::void_t<>>
struct IsToStringAvailable : std::false_type {};

template <typename T>
struct IsToStringAvailable<T, std::void_t<
    decltype(std::to_string(std::declval<T>()))>> : std::true_type {};

template <typename T>
using ValueTransferType = std::conditional_t<
    std::is_scalar_v<T>,
    T,
    std::conditional_t<IsString<T>::value,
        std::string_view,
        const T&>>;

template <typename T>
using ArrayReturnType = std::conditional_t<
    std::is_array_v<T>,
    std::add_pointer_t<std::remove_extent_t<T>>,
    T>;

template <typename PointerToMember>
struct MemberPointerTraits;

template <typename ClassType, typename DataType>
struct MemberPointerTraits<DataType ClassType::*>
{
    using Outer = ClassType;
    using T = DataType;
};


template <typename Outer>
struct StaticPropertyMeta;

template <typename T>
using IsObject = std::integral_constant<
    bool,
    StaticPropertyMeta<T>::getStaticPropertyMap() != nullptr>;

// ========================================================================
// reflection/utils/uniquestaticheterogeneousarray.h
// ========================================================================
template <typename Outer, std::size_t index>
struct UniqueStaticHeterogeneousArrayElement
{
    template <typename ValueT, ValueT value>
    struct Generator
    {
        friend constexpr auto getDefinedValue(UniqueStaticHeterogeneousArrayElement)
        { return value; }
    };

#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wnon-template-friend"
#pragma GCC diagnostic ignored "-Wunused-function"
#endif

    friend constexpr auto getDefinedValue(UniqueStaticHeterogeneousArrayElement);

#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif

    template <typename Tag = UniqueStaticHeterogeneousArrayElement, auto = getDefinedValue(Tag{})>
    static constexpr auto exists(std::size_t)
    { return true; }

    template <typename... Args>
    static constexpr auto exists(Args&&...)
    { return false; }

    template <typename ValueT, ValueT value, typename Tag = UniqueStaticHeterogeneousArrayElement, auto = getDefinedValue(Tag{})>
    static constexpr auto define(std::size_t)
    {
        return value;
    }

    template <typename ValueT, ValueT value, typename... Args>
    static constexpr auto define(Args&&...)
    {
        Generator<ValueT, value>();
        return value;
    }

    template <typename Tag = UniqueStaticHeterogeneousArrayElement, auto = getDefinedValue(Tag{})>
    static constexpr auto getValue(std::size_t)
    {
        return getDefinedValue(Tag{});
    }

    template <typename... Args>
    static constexpr auto getValue(Args&&...)
    {
        return nullptr;
    }
};

template <typename Outer, std::size_t index, typename Tag>
constexpr auto uniqueStaticHeterogeneousArrayExists(Tag)
{
    return UniqueStaticHeterogeneousArrayElement<Outer, index>::exists(index);
}

template <typename Outer, std::size_t index = 0, typename Tag>
constexpr auto uniqueStaticHeterogeneousArrayLength(Tag tag)
{
    if constexpr (!UniqueStaticHeterogeneousArrayElement<Outer, index>::exists(index))
        return index;
    else
        return uniqueStaticHeterogeneousArrayLength<Outer, index + 1, Tag>(tag);
}

template <typename Outer, std::size_t index, typename Tag>
constexpr auto uniqueStaticHeterogeneousArrayGetValue(Tag)
{
    return UniqueStaticHeterogeneousArrayElement<Outer, index>::getValue(index);
}

template <typename Outer, typename T, T value, typename Tag>
constexpr auto uniqueStaticHeterogeneousArrayPushBack(Tag tag)
{
    constexpr std::size_t insertIndex = uniqueStaticHeterogeneousArrayLength<Outer>(tag);
    return UniqueStaticHeterogeneousArrayElement<Outer, insertIndex>::
        template define<T, value>(insertIndex);
}

// ========================================================================
// reflection/utils/uniquestaticheterogeneousmap.h
// ========================================================================
template <typename Outer, typename KeyT, KeyT key>
struct UniqueStaticHeterogeneousMapElement
{
    using KeyType = ArrayReturnType<KeyT>;
    template <typename ValueT, ValueT value>
    struct Generator
    {
        friend constexpr auto getDefinedValue(UniqueStaticHeterogeneousMapElement)
        { return value; }
    };

#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wnon-template-friend"
#pragma GCC diagnostic ignored "-Wunused-function"
#endif

    friend constexpr auto getDefinedValue(UniqueStaticHeterogeneousMapElement);

#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif

    template <typename Tag = UniqueStaticHeterogeneousMapElement, auto = getDefinedValue(Tag{})>
    static constexpr auto exists(KeyT)
    { return true; }

    template <typename... Args>
    static constexpr auto exists(Args&&...)
    { return false; }

    template <typename ValueT, ValueT value, typename Tag = UniqueStaticHeterogeneousMapElement, auto = getDefinedValue(Tag{})>
    static constexpr auto define(KeyT)
    {
        return value;
    }

    template <typename ValueT, ValueT value, typename... Args>
    static constexpr auto define(Args&&...)
    {
        Generator<ValueT, value>();
        return value;
    }

    static constexpr KeyType getKey()
    {
        return key;
    }

    template <typename Tag = UniqueStaticHeterogeneousMapElement, auto = getDefinedValue(Tag{})>
    static constexpr auto getValue(KeyT)
    {
        return getDefinedValue(Tag{});
    }

    template <typename... Args>
    static constexpr auto getValue(Args&&...)
    {
        return nullptr;
    }
};

namespace impl
{

template <typename Outer, typename T>
struct UniqueStaticHeterogeneousMapKeyTag
{};

} // namespace impl

template <typename Outer, typename T, typename Tag>
constexpr auto uniqueStaticHeterogeneousMapKeysCount(Tag tag)
{
    return uniqueStaticHeterogeneousArrayLength<impl::UniqueStaticHeterogeneousMapKeyTag<Outer, T>>(tag);
}

template <typename Outer, typename T, T key, typename Tag>
constexpr auto uniqueStaticHeterogeneousMapExists(Tag)
{
    return UniqueStaticHeterogeneousMapElement<Outer, T, key>::exists(key);
}

template <typename Outer, typename T, T key, typename Tag>
constexpr auto uniqueStaticHeterogeneousMapGetValue(Tag)
{
    return UniqueStaticHeterogeneousMapElement<Outer, T, key>::getValue(key);
}

template <typename Outer, typename T, typename U, T key, U value, typename Tag>
constexpr auto uniqueStaticHeterogeneousMapAdd(Tag tag)
{
    if constexpr (!UniqueStaticHeterogeneousMapElement<Outer, T, key>::exists(key))
    {
        uniqueStaticHeterogeneousArrayPushBack<impl::UniqueStaticHeterogeneousMapKeyTag<Outer, T>, T, key>(tag);
        return UniqueStaticHeterogeneousMapElement<Outer, T, key>::template define<U, value>();
    }
    else
    {
        return value;
    }
}

namespace impl
{

struct UniqueStaticHeterogeneousMapElementTrueChecker
{
    template <typename...>
    using Filter = std::true_type;
};

template <typename TInKey, typename TTestKey>
struct UniqueStaticHeterogeneousMapElementKeyChecker
{
    template <typename /* Outer */, typename T, typename TKey, typename /* TValue */>
    using Filter = std::bool_constant<TKey::value == TTestKey::value>;
};

template <typename Outer, typename T, typename TypeChecker,
    typename F, std::size_t index, typename Tag>
void uniqueStaticHeterogeneousMapForEachImpl(Tag tag, F&& func)
{
    if constexpr (index >= uniqueStaticHeterogeneousMapKeysCount<Outer, T>(tag))
    {
        return;
    }
    else
    {
        constexpr auto key = uniqueStaticHeterogeneousArrayGetValue<impl::UniqueStaticHeterogeneousMapKeyTag<Outer, T>, index>(tag);
        constexpr auto value = uniqueStaticHeterogeneousMapGetValue<Outer, T, key>(tag);
        using Key = std::integral_constant<decltype(key), key>;
        using Value = std::integral_constant<decltype(value), value>;
        using Filter = typename TypeChecker::template Filter<Outer, T, Key, Value>;

        if constexpr (Filter::value)
        {
            using FuncRet = decltype(func(Key{}, Value{}));

            if constexpr (std::is_same_v<FuncRet, bool>)
            {
                if (!func(Key{}, Value{}))
                {
                    return;
                }
            }
            else if constexpr (std::is_void_v<FuncRet>)
            {
                func(Key{}, Value{});
            }
            else
            {
                static_assert(false, "Unexpected func return type");
            }
        }

        uniqueStaticHeterogeneousMapForEachImpl<Outer, T, TypeChecker, F, index + 1, Tag>(tag, std::forward<F>(func));
    }
}

template <typename Outer, typename T, typename TypeChecker,
    typename F, typename P, std::size_t index, typename Tag>
void uniqueStaticHeterogeneousMapForEachIfImpl(Tag tag, F&& func, P&& pred)
{
    if constexpr (index >= uniqueStaticHeterogeneousMapKeysCount<Outer, T>(tag))
    {
        return;
    }
    else
    {
        constexpr auto key = uniqueStaticHeterogeneousArrayGetValue<impl::UniqueStaticHeterogeneousMapKeyTag<Outer, T>, index>(tag);
        constexpr auto value = uniqueStaticHeterogeneousMapGetValue<Outer, T, key>(tag);
        using Key = std::integral_constant<decltype(key), key>;
        using Value = std::integral_constant<decltype(value), value>;
        using Filter = typename TypeChecker::template Filter<Outer, T, Key, Value>;

        if constexpr (Filter::value)
        {
            using FuncRet = decltype(func(Key{}, Value{}));

            if (pred(Key{}, Value{}))
            {
                if constexpr (std::is_same_v<FuncRet, bool>)
                {
                    if (!func(Key{}, Value{}))
                    {
                        return;
                    }
                }
                else if constexpr (std::is_void_v<FuncRet>)
                {
                    func(Key{}, Value{});
                }
                else
                {
                    static_assert(false, "Unexpected func return type");
                }
            }
        }

        uniqueStaticHeterogeneousMapForEachIfImpl<Outer, T, TypeChecker, F, P, index + 1, Tag>(tag, std::forward<F>(func), std::forward<P>(pred));
    }
}

} // namespace impl

/**
 * @brief perform a function for each element
 * @param tag empty lambda
 * @param func delegate to iterate over elements, can return void or bool, in such case false means break
 */
template <typename Outer, typename T,
    typename TypeChecker = impl::UniqueStaticHeterogeneousMapElementTrueChecker,
    typename F, typename Tag>
void uniqueStaticHeterogeneousMapForEach(Tag tag, F&& func)
{
    using CleanF = std::decay_t<F>;

    if constexpr (std::is_convertible_v<CleanF, std::nullptr_t>)
    {
        if (func == nullptr)
        {
            return;
        }
    }

    impl::uniqueStaticHeterogeneousMapForEachImpl<Outer, T, TypeChecker, F, 0>(
        tag, std::forward<F>(func));
}

/**
 * @brief perform a function for each element that satisfies predicate condition
 * @param tag empty lambda
 * @param func delegate to iterate over elements, can return void or bool, in such case false means break
 * @param pred predicate, that defines which elements are passed to func (true) or skipped (false)
 */
template <typename Outer, typename T,
    typename TypeChecker = impl::UniqueStaticHeterogeneousMapElementTrueChecker,
    typename F, typename P, typename Tag>
void uniqueStaticHeterogeneousMapForEachIf(Tag tag, F&& func, P&& pred)
{
    using CleanF = std::decay_t<F>;

    if constexpr (std::is_convertible_v<CleanF, std::nullptr_t>)
    {
        if (func == nullptr)
        {
            return;
        }
    }

    using CleanP = std::decay_t<P>;

    if constexpr (std::is_convertible_v<CleanP, std::nullptr_t>)
    {
        if (pred == nullptr)
        {
            return;
        }
    }

    impl::uniqueStaticHeterogeneousMapForEachIfImpl<Outer, T, TypeChecker, F, P, 0>(
        tag, std::forward<F>(func), std::forward<P>(pred));
}

template <typename Outer, typename T,
    typename Comparator = std::equal_to<void>,
    typename TypeChecker = impl::UniqueStaticHeterogeneousMapElementTrueChecker,
    typename F, typename Tag>
void uniqueStaticHeterogeneousMapDoForKey(Tag tag, F&& func, T key, Comparator comparator = Comparator())
{
    uniqueStaticHeterogeneousMapForEachIf<Outer, T, TypeChecker>(tag, [&func](auto constKey, auto constValue)
    {
        func(constKey, constValue);
        return false;
    }, [&key, &comparator](auto constKey, auto)
    {
        constexpr auto currentKey = decltype(constKey)::value;
        return comparator(key, currentKey);
    });
}

template <typename Outer, typename T, T key, typename F, typename Tag>
void uniqueStaticHeterogeneousMapDoForKey(Tag tag, F&& func)
{
    using KeyChecker = impl::UniqueStaticHeterogeneousMapElementKeyChecker<
        T, std::integral_constant<ArrayReturnType<T>, key>>;
    uniqueStaticHeterogeneousMapForEach<Outer, T, KeyChecker>(tag, func);
}

// ========================================================================
// reflection/property/basestaticproperty.h
// ========================================================================
template <typename Outer>
struct BaseStaticProperty
{
    using ThisClass = BaseStaticProperty<Outer>;

    const std::string_view name;
};

// ========================================================================
// reflection/property/staticproperty.h
// ========================================================================
template <typename Outer, typename T>
struct StaticProperty : public BaseStaticProperty<Outer>
{
    using BaseClass = BaseStaticProperty<Outer>;
    using ThisClass = StaticProperty<Outer, T>;
    using OuterClass = Outer;
    using ValueType = T;
    using ValueTransferType = typename reflection::ValueTransferType<T>;
    using ValuePtr = T Outer::*;

    ValueTransferType get(const Outer& outer) const noexcept
    {
        return outer.*valuePtr;
    }
    const ThisClass& set(Outer& outer, T&& value) const noexcept
    {
        outer.*valuePtr = std::move(value);
        return *this;
    }
    const ThisClass& set(Outer& outer, ValueTransferType value) const noexcept
    {
        outer.*valuePtr = value;
        return *this;
    }

    const ValuePtr valuePtr;
};

// ========================================================================
// reflection/property/staticpropertymap.h
// ========================================================================
template <typename Outer>
struct StaticPropertyMap : public BaseStaticProperty<Outer>
{
    using BaseClass = BaseStaticProperty<Outer>;
    using ThisClass = StaticPropertyMap<Outer>;
    using OuterClass = Outer;
};

// ========================================================================
// reflection/property/staticpropertyproxy.h
// ========================================================================
template <typename Outer, typename StaticPropertyT>
struct StaticPropertyProxy : public BaseStaticProperty<Outer>
{
    using BaseClass = BaseStaticProperty<Outer>;
    using ThisClass = StaticPropertyProxy<Outer, StaticPropertyT>;
    using OuterClass = Outer;
    using TargetStaticPropertyClass = StaticPropertyT;
    using TargetOuterClass = typename TargetStaticPropertyClass::OuterClass;

    const TargetStaticPropertyClass& staticProperty;
};

// ========================================================================
// reflection/property/staticpropertymeta.h
// ========================================================================
namespace impl
{

template <typename Outer, typename T,
    const char rawName[], T Outer::* valuePtr>
struct StaticPropertyHolder
{
    using StaticPropertyType = reflection::StaticProperty<Outer, T>;
    static constexpr StaticPropertyType staticProperty
    {
        { rawName },
        valuePtr
    };
};

template <typename Outer, const char rawName[]>
struct StaticPropertyMapHolder
{
    using StaticPropertyType = reflection::StaticPropertyMap<Outer>;
    static constexpr StaticPropertyType staticProperty
    {
        { rawName }
    };
};

template <typename Outer, typename StaticPropertyT,
    const char rawName[], const StaticPropertyT& targetStaticProperty>
struct StaticPropertyProxyHolder
{
    using StaticPropertyType = reflection::StaticPropertyProxy<Outer, StaticPropertyT>;
    static constexpr StaticPropertyType staticProperty
    {
        { rawName },
        targetStaticProperty
    };
};

template <const char rawName[], auto valuePtr>
using DefineStaticProperty = StaticPropertyHolder<
    typename MemberPointerTraits<decltype(valuePtr)>::Outer,
    typename MemberPointerTraits<decltype(valuePtr)>::T,
    rawName,
    valuePtr>;

template <typename Outer, const char rawName[]>
using DefineStaticPropertyMap = StaticPropertyMapHolder<
    Outer, rawName>;

template <typename Outer, const char rawName[], const auto& targetStaticProperty>
using DefineStaticPropertyProxy = StaticPropertyProxyHolder<
    Outer,
    std::remove_cv_t<std::remove_reference_t<decltype(targetStaticProperty)>>,
    rawName,
    targetStaticProperty>;


auto getNonintrusiveReflectionDeclarator(...) -> std::true_type;

template <typename T>
using NonintrusiveReflectionDeclarator = decltype(
    getNonintrusiveReflectionDeclarator(
        static_cast<T*>(nullptr)));

auto getNonintrusiveReflectionInheritanceDeclarator(...)
    -> std::true_type;

template <typename T>
using NonintrusiveReflectionInheritanceDeclarator = decltype(
    getNonintrusiveReflectionInheritanceDeclarator(
        static_cast<T**>(nullptr)));

} // namespace impl

template <typename Outer>
struct StaticPropertyMeta
{
    using ThisClass = StaticPropertyMeta<Outer>;
    using OuterClass = Outer;
    using KeyType = const char[];
    using DefaultTypeChecker = impl::UniqueStaticHeterogeneousMapElementTrueChecker;

    static constexpr KeyType staticStorageKey{ "" };

    static constexpr auto size() noexcept
    {
        return uniqueStaticHeterogeneousMapKeysCount<ThisClass, KeyType>([]{});
    }

    static constexpr bool empty() noexcept
    {
        return size() == 0;
    }

    template <KeyType propertyName>
    static constexpr auto contains()
    {
        constexpr auto canonicalPropertyName =
            CanonicalStaticString<propertyName>::value;
        return uniqueStaticHeterogeneousMapExists<
            ThisClass, KeyType, canonicalPropertyName>([]{});
    }

    static constexpr auto getStaticPropertyMap()
    {
        return uniqueStaticHeterogeneousMapGetValue<
            StaticPropertyMap<Outer>, KeyType, staticStorageKey>([]{});
    }

    template <KeyType propertyName>
    static constexpr auto at()
    {
        constexpr auto canonicalPropertyName =
            CanonicalStaticString<propertyName>::value;
        return uniqueStaticHeterogeneousMapGetValue<ThisClass, KeyType, canonicalPropertyName>([]{});
    }

    template <typename TypeChecker = DefaultTypeChecker,
        typename F>
    static void forEach(F&& func)
    {
        uniqueStaticHeterogeneousMapForEach<
            ThisClass, KeyType, TypeChecker>(
                []{}, std::forward<F>(func));
    }

    template <typename TypeChecker = DefaultTypeChecker,
        typename F, typename P>
    static void forEachIf(F&& func, P&& pred)
    {
        uniqueStaticHeterogeneousMapForEachIf<
            ThisClass, KeyType, TypeChecker>(
                []{}, std::forward<F>(func), std::forward<P>(pred));
    }

    template <typename Comparator = std::equal_to<void>,
        typename TypeChecker = DefaultTypeChecker,
        typename F>
    static void doForKey(F&& func, KeyType key, Comparator comparator = Comparator())
    {
        uniqueStaticHeterogeneousMapDoForKey<
            ThisClass, KeyType, Comparator, TypeChecker>(
                []{}, std::forward<F>(func), key, comparator);
    }

    template <KeyType key, typename F>
    static void doForKey(F&& func)
    {
        uniqueStaticHeterogeneousMapDoForKey<
            ThisClass, KeyType, key>(
                []{}, std::forward<F>(func));
    }

    template <KeyType propertyName>
    static constexpr auto defineStaticPropertyMap()
    {
        using Holder = impl::DefineStaticPropertyMap<Outer, propertyName>;
        using StaticPropertyType = typename Holder::StaticPropertyType;
        constexpr auto staticPropertyPtr = &Holder::staticProperty;
        return uniqueStaticHeterogeneousMapAdd<
            StaticPropertyMap<Outer>, KeyType, const StaticPropertyType*, staticStorageKey, staticPropertyPtr>([]{});
    }

    template <KeyType propertyName, auto valuePtr>
    static constexpr auto defineStaticProperty()
    {
        using Holder = impl::DefineStaticProperty<propertyName, valuePtr>;
        using StaticPropertyType = typename Holder::StaticPropertyType;
        constexpr auto canonicalPropertyName = CanonicalStaticString<propertyName>::value;
        constexpr auto staticPropertyPtr = &Holder::staticProperty;
        return uniqueStaticHeterogeneousMapAdd<
            ThisClass, KeyType, const StaticPropertyType*, canonicalPropertyName, staticPropertyPtr>([]{});
    }

    template <KeyType propertyName, const auto& targetStaticProperty>
    static constexpr auto defineStaticPropertyProxy()
    {
        using Holder = impl::DefineStaticPropertyProxy<Outer, propertyName, targetStaticProperty>;
        using StaticPropertyType = typename Holder::StaticPropertyType;
        constexpr auto canonicalPropertyName = CanonicalStaticString<propertyName>::value;
        constexpr auto staticPropertyPtr = &Holder::staticProperty;
        return uniqueStaticHeterogeneousMapAdd<
            ThisClass, KeyType, const StaticPropertyType*, canonicalPropertyName, staticPropertyPtr>([]{});
    }

    template <KeyType propertyNames, auto... valuePtrs>
    static constexpr bool defineStaticPropertyMulti()
    {
        using Parser = CanonicalPropertyNameParser<propertyNames>;

        static_assert(
            Parser::count == sizeof...(valuePtrs),
            "defineStaticPropertyMulti: "
            "property names count doesn't match value pointers count");

        return defineStaticPropertyMultiImpl<
            propertyNames,
            0,
            valuePtrs...>();
    }

    template <KeyType namePrefix, KeyType baseClassNames, typename... BaseClasses>
    static constexpr bool defineBaseClassMulti()
    {
        using Parser = CanonicalPropertyNameParser<baseClassNames>;

        static_assert(
            Parser::count == sizeof...(BaseClasses),
            "defineBaseClassMulti: "
            "base class names count doesn't match base class types count");

        return defineBaseClassMultiImpl<
            namePrefix, baseClassNames, 0, BaseClasses...>();
    }

private:
    template <
        KeyType propertyNames,
        std::size_t propertyIndex,
        auto valuePtr,
        auto... valuePtrs>
    static constexpr auto defineStaticPropertyMultiImpl()
    {
        using Parser = CanonicalPropertyNameParser<propertyNames>;

        static_assert(
            propertyIndex < Parser::count,
            "defineStaticPropertyMultiImpl: propertyIndex is out of range");

        using PropertyName =
            typename Parser::template CanonicalName<propertyIndex>;

        constexpr auto staticPropertyPtr =
            defineStaticProperty<PropertyName::value, valuePtr>();

        static_assert(
            staticPropertyPtr != nullptr,
            "defineStaticPropertyMultiImpl: failed to define static property");

        if constexpr (sizeof...(valuePtrs) == 0)
        {
            return true;
        }
        else
        {
            return defineStaticPropertyMultiImpl<
                propertyNames,
                propertyIndex + 1,
                valuePtrs...>();
        }
    }

    template <
        KeyType namePrefix,
        KeyType baseClassNames,
        std::size_t baseClassIndex,
        typename BaseClass,
        typename... BaseClasses>
    static constexpr bool defineBaseClassMultiImpl()
    {
        using Parser = CanonicalPropertyNameParser<baseClassNames>;

        static_assert(
            baseClassIndex < Parser::count,
            "defineBaseClassMultiImpl: baseClassIndex is out of range");

        using BaseClassName =
            CanonicalStaticStringConcat<
                namePrefix,
                Parser::template CanonicalName<baseClassIndex>::value>;

        constexpr auto baseStaticPropertyMapPtr =
            StaticPropertyMeta<BaseClass>::getStaticPropertyMap();

        static_assert(
            baseStaticPropertyMapPtr != nullptr,
            "defineBaseClassMultiImpl: base class does not have static property map");

        constexpr auto staticPropertyPtr =
            defineStaticPropertyProxy<BaseClassName::value, *baseStaticPropertyMapPtr>();

        static_assert(
            staticPropertyPtr != nullptr,
            "defineBaseClassMultiImpl: failed to define base class proxy");

        if constexpr (sizeof...(BaseClasses) == 0)
        {
            return true;
        }
        else
        {
            return defineBaseClassMultiImpl<
                namePrefix,
                baseClassNames,
                baseClassIndex + 1,
                BaseClasses...>();
        }
    }

    static_assert(
        sizeof(impl::NonintrusiveReflectionDeclarator<Outer>) > 0); // NOLINT(bugprone-sizeof-expression)

    static_assert(
        sizeof(impl::NonintrusiveReflectionInheritanceDeclarator<Outer>) > 0); // NOLINT(bugprone-sizeof-expression)
};

} // namespace reflection

// ========================================================================
// reflection/reflection.h
// ========================================================================
#define REFLECTION_UNPAREN(...) __VA_ARGS__

#define DECL_PROPERTY_NAME_WRAPPER(FieldName, FieldRawName) \
    struct Reflection_MetaInfo_ ## FieldName \
    { \
        static constexpr char propertyName[]{ FieldRawName }; \
    };

#define DECL_VALUE(Type, FieldName, InitialValue) \
    Type FieldName{ InitialValue };

#define DECL_VALUE_DEFAULT(Type, FieldName) \
    Type FieldName{};

#define DECL_STATIC_PROPERTY(FieldName) \
    DECL_PROPERTY_NAME_WRAPPER(FieldName, #FieldName) \
    static_assert([]() constexpr \
    { \
        using Meta = reflection::StaticPropertyMeta<ThisClass>; \
        using MetaInfo = Reflection_MetaInfo_ ## FieldName; \
        constexpr auto staticPropertyPtr = Meta::template defineStaticProperty< \
            MetaInfo::propertyName, &ThisClass::FieldName>(); \
        return staticPropertyPtr != nullptr; \
    }());

#define DECL_PROPERTY_INIT(Type, FieldName, InitialValue) \
    DECL_VALUE(Type, FieldName, InitialValue) \
    DECL_STATIC_PROPERTY(FieldName) \

#define DECL_PROPERTY_DEFAULT(Type, FieldName) \
    DECL_VALUE_DEFAULT(Type, FieldName) \
    DECL_STATIC_PROPERTY(FieldName) \


#define DECL_BASE_CLASS_INIT(BaseClassType, BaseClassRawName) \
    DECL_PROPERTY_NAME_WRAPPER(Base_ ## BaseClassType, BaseClassRawName) \
    static_assert([]() constexpr \
    { \
        using Meta = reflection::StaticPropertyMeta<ThisClass>; \
        using BaseMeta = reflection::StaticPropertyMeta<BaseClassType>; \
        using MetaInfo = Reflection_MetaInfo_Base_ ## BaseClassType; \
        constexpr auto baseStaticPropertyMapPtr = BaseMeta::getStaticPropertyMap(); \
        if constexpr (baseStaticPropertyMapPtr == nullptr) { \
            return false; \
        } else { \
            constexpr auto staticPropertyPtr = Meta::template defineStaticPropertyProxy< \
                MetaInfo::propertyName, *baseStaticPropertyMapPtr>(); \
            return staticPropertyPtr != nullptr; \
        } \
    }());

#define DECL_BASE_CLASS(BaseClassType) \
    DECL_BASE_CLASS_INIT(BaseClassType, "_base_" #BaseClassType)


#define DECL_STATIC_PROPERTY_MAP(ClassType, ClassRawName) \
    DECL_PROPERTY_NAME_WRAPPER(ClassType, ClassRawName) \
    static_assert([]() constexpr \
    { \
        using Meta = reflection::StaticPropertyMeta<ThisClass>; \
        using MetaInfo = Reflection_MetaInfo_ ## ClassType; \
        constexpr auto staticPropertyPtr = Meta::template defineStaticPropertyMap< \
            MetaInfo::propertyName>(); \
        return staticPropertyPtr != nullptr; \
    }());

#define DECL_REFLECTION_BODY(ClassType) \
    using ThisClass = ClassType; \
    DECL_STATIC_PROPERTY_MAP(ClassType, #ClassType)


#define DECL_PROPERTY_NAME_WRAPPER_MULTI(...) \
    struct Reflection_MetaInfo \
    { \
        static constexpr char propertyNames[]{ #__VA_ARGS__ }; \
    };

#define DECL_STATIC_PROPERTY_MULTI(...) \
    DECL_PROPERTY_NAME_WRAPPER_MULTI(__VA_ARGS__) \
    static_assert([]() constexpr \
    { \
        using Meta = reflection::StaticPropertyMeta<ThisClass>; \
        return Meta::template defineStaticPropertyMulti< \
            Reflection_MetaInfo::propertyNames, __VA_ARGS__>(); \
    }());

#define DECL_REFLECTION_NONINTRUSIVE(ClassType, ...) \
    namespace reflection_nonintrusive_ ## ClassType \
    { \
        using ThisClass = ClassType; \
        DECL_STATIC_PROPERTY_MAP(ClassType, #ClassType) \
        DECL_STATIC_PROPERTY_MULTI(__VA_ARGS__) \
    }

#define DECL_REFLECTION_TEMPLATE_NONINTRUSIVE(TemplateDeclaration, TemplateArguments, ClassType, ...) \
    namespace reflection_nonintrusive_ ## ClassType \
    { \
        template <REFLECTION_UNPAREN TemplateDeclaration> \
        struct ReflectionDeclarator \
        { \
            using ThisClass = ClassType<REFLECTION_UNPAREN TemplateArguments>; \
            DECL_STATIC_PROPERTY_MAP(ClassType, #ClassType) \
            DECL_STATIC_PROPERTY_MULTI(__VA_ARGS__) \
        }; \
    } \
    template <REFLECTION_UNPAREN TemplateDeclaration> \
        auto getNonintrusiveReflectionDeclarator( \
            ClassType<REFLECTION_UNPAREN TemplateArguments>*) \
        -> reflection_nonintrusive_ ## ClassType::ReflectionDeclarator< \
            REFLECTION_UNPAREN TemplateArguments>;


#define DECL_BASE_CLASS_MULTI(NamePrefix, ...) \
    struct Reflection_BaseMetaInfo \
    { \
        static constexpr char namePrefix[]{ NamePrefix }; \
        static constexpr char baseClassNames[]{ #__VA_ARGS__ }; \
    }; \
    static_assert([]() constexpr \
    { \
        using Meta = reflection::StaticPropertyMeta<ThisClass>; \
        return Meta::template defineBaseClassMulti< \
            Reflection_BaseMetaInfo::namePrefix, \
            Reflection_BaseMetaInfo::baseClassNames, \
            __VA_ARGS__>(); \
    }());

#define DECL_REFLECTION_INHERITANCE_INIT_NONINTRUSIVE(ClassType, NamePrefix, ...) \
    namespace reflection_nonintrusive_ ## ClassType \
    { \
        using ThisClass = ClassType; \
        DECL_BASE_CLASS_MULTI(NamePrefix, __VA_ARGS__) \
    }

#define DECL_REFLECTION_INHERITANCE_NONINTRUSIVE(ClassType, ...) \
    DECL_REFLECTION_INHERITANCE_INIT_NONINTRUSIVE(ClassType, "_base_", __VA_ARGS__)

#define DECL_REFLECTION_INHERITANCE_INIT_TEMPLATE_NONINTRUSIVE( \
    TemplateDeclaration, TemplateArguments, ClassType, NamePrefix, ...) \
        namespace reflection_nonintrusive_ ## ClassType \
        { \
            template <REFLECTION_UNPAREN TemplateDeclaration> \
            struct ReflectionInheritanceDeclarator \
            { \
                using ThisClass = ClassType<REFLECTION_UNPAREN TemplateArguments>; \
                DECL_BASE_CLASS_MULTI(NamePrefix, __VA_ARGS__) \
            }; \
        } \
        template <REFLECTION_UNPAREN TemplateDeclaration> \
        auto getNonintrusiveReflectionInheritanceDeclarator( \
            ClassType<REFLECTION_UNPAREN TemplateArguments>**) \
        -> reflection_nonintrusive_ ## ClassType::ReflectionInheritanceDeclarator< \
            REFLECTION_UNPAREN TemplateArguments>;

#define DECL_REFLECTION_INHERITANCE_TEMPLATE_NONINTRUSIVE( \
    TemplateDeclaration, TemplateArguments, ClassType, ...) \
        DECL_REFLECTION_INHERITANCE_INIT_TEMPLATE_NONINTRUSIVE( \
            TemplateDeclaration, TemplateArguments, ClassType, "_base_", __VA_ARGS__)
